on:
  push:
    branches:
      - portfolio
jobs:
  deploy-to-portfolio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and push image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u ${{ github.actor }} ghcr.io --password-stdin
          docker build -t ghcr.io/${{github.repository}}/melee:latest .
          docker push ghcr.io/${{github.repository}}/melee:latest

      - name: Deploy to Linode
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u ${{ github.actor }} ghcr.io --password-stdin
            docker pull ghcr.io/${{github.repository}}/melee:latest
            docker stop melee || true
            docker rm melee || true
            docker run -d -p 3000:80 --name melee --restart unless-stopped ghcr.io/${{github.repository}}/melee:latest
